import { routeTree } from '@tanstack/react-router'

// This file is generated by the TanStack Router Vite plugin.
// Do not edit this file manually.

// This is a placeholder for the generated route tree.
// The actual route tree will be generated by the plugin.
